### ISSUE TITLE
请问这个检验过程中的API怎么获得？

### ISSUE THREAD

**Issue by robin087** [RUCKBReasoning/DialEvaluation#1]
在获得模型生成结果时，是调用的各个模型的API，请问有怎么搭建这个API的说明吗？

谢谢！

**Comment by Kaka23333** [comment]
您好
论文中使用的中文开源模型CDial-GPT、EVA2.0和GLM10B在其对应的github主页均有搭建方式。对于系统后端与对话模型交互的API格式，我已经上传了新的md文件，具体可参考model_api_format.md

**Comment by robin087** [comment]
感谢您的回复，我去参考对应的模型尝试搭建一下，谢谢
